# Generated by Django 4.2.25 on 2025-11-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Minimum 50 characters')),
                ('job_role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('designer', 'UI/UX Designer'), ('data_scientist', 'Data Scientist'), ('project_manager', 'Project Manager'), ('marketing', 'Marketing Specialist'), ('sales', 'Sales Executive'), ('hr', 'HR Manager'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], max_length=20)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('1-2', '1-2 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('vacancies', models.CharField(choices=[('1', '1'), ('2-5', '2-5'), ('6-10', '6-10'), ('10+', '10+')], max_length=10)),
                ('expiration_date', models.DateField()),
                ('job_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('manager', 'Manager'), ('executive', 'Executive')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('responsibilities', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['-posted_at'], name='jobs_job_posted__7d11dc_idx'), models.Index(fields=['employer', 'status'], name='jobs_job_employe_9a6de3_idx')],
            },
        ),
    ]
