# Generated by Django 4.2.25 on 2025-11-25 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tags', to='jobs.job')),
            ],
            options={
                'ordering': ['tag_name'],
                'unique_together': {('job', 'tag_name')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('applicant_notes', models.TextField(blank=True, help_text='Cover letter or additional notes from the applicant')),
                ('employer_rating', models.IntegerField(blank=True, help_text='Rating given by employer (1-5)', null=True)),
                ('hired_date', models.DateField(blank=True, help_text="Date when status changed to 'hired'", null=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-application_date'],
                'indexes': [models.Index(fields=['applicant', 'status'], name='jobs_jobapp_applica_089491_idx'), models.Index(fields=['job', 'status'], name='jobs_jobapp_job_id_08192b_idx'), models.Index(fields=['-application_date'], name='jobs_jobapp_applica_e243e0_idx')],
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
