# Generated by Django 4.2.25 on 2025-11-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobtag_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for programmatic reference', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the education level', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this level is currently available')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for programmatic reference', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the employment type', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this type is currently available')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Employment Type',
                'verbose_name_plural': 'Employment Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for programmatic reference', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the experience level', max_length=100)),
                ('min_years', models.PositiveSmallIntegerField(blank=True, help_text='Minimum years of experience', null=True)),
                ('max_years', models.PositiveSmallIntegerField(blank=True, help_text='Maximum years of experience', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this level is currently available')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Experience Level',
                'verbose_name_plural': 'Experience Levels',
                'ordering': ['order', 'min_years'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for programmatic reference', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the category', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently available')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for programmatic reference', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the job level', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this level is currently available')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Job Level',
                'verbose_name_plural': 'Job Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for programmatic reference', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the salary type', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this type is currently available')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Salary Type',
                'verbose_name_plural': 'Salary Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobtag',
            options={'ordering': ['tag__name'], 'verbose_name': 'Job Tag', 'verbose_name_plural': 'Job Tags'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_role',
        ),
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateField(help_text='Application deadline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, help_text='Legacy tags field, replaced by Many-to-Many Tag relationship', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.SmallIntegerField(default=1, help_text='Number of open positions'),
        ),
        migrations.AlterField(
            model_name='jobtag',
            name='job',
            field=models.ForeignKey(help_text='The job this tag is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='job_tags', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='jobs_tag_name_95da66_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='jobs_tag_slug_a8ae84_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active'], name='jobs_tag_is_acti_76052a_idx'),
        ),
        migrations.AddIndex(
            model_name='salarytype',
            index=models.Index(fields=['code'], name='jobs_salary_code_c8c183_idx'),
        ),
        migrations.AddIndex(
            model_name='salarytype',
            index=models.Index(fields=['is_active', 'order'], name='jobs_salary_is_acti_4a23bc_idx'),
        ),
        migrations.AddIndex(
            model_name='joblevel',
            index=models.Index(fields=['code'], name='jobs_joblev_code_24944f_idx'),
        ),
        migrations.AddIndex(
            model_name='joblevel',
            index=models.Index(fields=['is_active', 'order'], name='jobs_joblev_is_acti_7b1c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['code'], name='jobs_jobcat_code_efaf49_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['is_active', 'order'], name='jobs_jobcat_is_acti_d56492_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencelevel',
            index=models.Index(fields=['code'], name='jobs_experi_code_49e86e_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencelevel',
            index=models.Index(fields=['is_active', 'order'], name='jobs_experi_is_acti_f2ad25_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenttype',
            index=models.Index(fields=['code'], name='jobs_employ_code_ecc00c_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenttype',
            index=models.Index(fields=['is_active', 'order'], name='jobs_employ_is_acti_4ed0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='educationlevel',
            index=models.Index(fields=['code'], name='jobs_educat_code_5f2ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='educationlevel',
            index=models.Index(fields=['is_active', 'order'], name='jobs_educat_is_acti_eaac06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Job category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobtag',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='The tag associated with this job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tags', to='jobs.tag'),
        ),
        migrations.AddIndex(
            model_name='jobtag',
            index=models.Index(fields=['job', 'tag'], name='jobs_jobtag_job_id_86a3d3_idx'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.ForeignKey(blank=True, help_text='Required education level', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.educationlevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='Required experience level', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.experiencelevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(blank=True, help_text='Seniority level of the position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.joblevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(blank=True, help_text='Type of employment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.employmenttype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.ForeignKey(blank=True, help_text='Salary payment frequency', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.salarytype'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtag',
            unique_together={('job', 'tag')},
        ),
        migrations.RemoveField(
            model_name='jobtag',
            name='tag_name',
        ),
    ]
