# Generated by Django 4.2.25 on 2025-11-26 14:42

from django.db import migrations


def populate_lookup_tables(apps, schema_editor):
    """Populate lookup tables with initial data."""
    
    # Get models
    JobCategory = apps.get_model('jobs', 'JobCategory')
    EmploymentType = apps.get_model('jobs', 'EmploymentType')
    EducationLevel = apps.get_model('jobs', 'EducationLevel')
    ExperienceLevel = apps.get_model('jobs', 'ExperienceLevel')
    JobLevel = apps.get_model('jobs', 'JobLevel')
    SalaryType = apps.get_model('jobs', 'SalaryType')
    
    # Job Categories
    categories = [
        {'code': 'tech_software', 'name': 'Technology & Software Development', 'order': 1},
        {'code': 'design_media', 'name': 'Design, Creative & Media', 'order': 2},
        {'code': 'marketing_pr', 'name': 'Marketing, Advertising & PR', 'order': 3},
        {'code': 'sales_bizdev', 'name': 'Sales & Business Development', 'order': 4},
        {'code': 'finance_acct', 'name': 'Finance & Accounting', 'order': 5},
        {'code': 'hr_admin', 'name': 'Human Resources & Administration', 'order': 6},
        {'code': 'operations', 'name': 'Operations, Supply Chain & Logistics', 'order': 7},
        {'code': 'healthcare', 'name': 'Healthcare & Medical', 'order': 8},
        {'code': 'education', 'name': 'Education & Training', 'order': 9},
        {'code': 'legal', 'name': 'Legal', 'order': 10}, 
        {'code': 'customer_service', 'name': 'Customer Service', 'order': 11},
        {'code': 'manual_labor', 'name': 'Skilled Trades & Manual Labor', 'order': 12}, 
        {'code': 'other', 'name': 'Other / General', 'order': 13},
    ]
    JobCategory.objects.bulk_create([JobCategory(**cat) for cat in categories])
    
    # Employment Types
    employment_types = [
        {'code': 'full_time', 'name': 'Full-Time', 'order': 1},
        {'code': 'part_time', 'name': 'Part-Time', 'order': 2},
        {'code': 'contract', 'name': 'Contract', 'order': 3},
        {'code': 'freelance', 'name': 'Freelance / Gig', 'order': 4},
        {'code': 'internship', 'name': 'Internship', 'order': 5},
        {'code': 'temporary', 'name': 'Temporary / Seasonal', 'order': 6}, 
    ]
    EmploymentType.objects.bulk_create([EmploymentType(**emp_type) for emp_type in employment_types])
    
    # Education Levels
    education_levels = [
        {'code': 'none', 'name': 'None', 'order': 1},
        {'code': 'high_school', 'name': 'High School / GED', 'order': 2},
        {'code': 'associate', 'name': "Associate's Degree", 'order': 3}, 
        {'code': 'bachelor', 'name': "Bachelor's Degree", 'order': 4}, 
        {'code': 'master', 'name': "Master's Degree", 'order': 5}, 
        {'code': 'phd_doctorate', 'name': 'Doctorate (PhD/MD/JD/EdD)', 'order': 6},
        {'code': 'vocational', 'name': 'Vocational Training / Certification', 'order': 7},
    ]
    EducationLevel.objects.bulk_create([EducationLevel(**edu) for edu in education_levels])
    
    # Experience Levels
    experience_levels = [
        {'code': 'entry', 'name': '0-2 Years (Entry)', 'min_years': 0, 'max_years': 2, 'order': 1},
        {'code': 'mid', 'name': '3-5 Years (Mid)', 'min_years': 3, 'max_years': 5, 'order': 2},
        {'code': 'senior', 'name': '6-9 Years (Senior)', 'min_years': 6, 'max_years': 9, 'order': 3},
        {'code': 'expert', 'name': '10+ Years (Expert)', 'min_years': 10, 'max_years': None, 'order': 4},
    ]
    ExperienceLevel.objects.bulk_create([ExperienceLevel(**exp) for exp in experience_levels])
    
    # Job Levels
    job_levels = [
        {'code': 'intern', 'name': 'Intern', 'order': 1},
        {'code': 'entry', 'name': 'Entry Level', 'order': 2},
        {'code': 'mid', 'name': 'Mid Level', 'order': 3},
        {'code': 'senior', 'name': 'Senior', 'order': 4},
        {'code': 'lead', 'name': 'Lead / Supervisor', 'order': 5},
        {'code': 'manager', 'name': 'Manager', 'order': 6},
        {'code': 'director', 'name': 'Director / VP', 'order': 7},
        {'code': 'executive', 'name': 'Executive (C-Suite)', 'order': 8},
    ]
    JobLevel.objects.bulk_create([JobLevel(**level) for level in job_levels])
    
    # Salary Types
    salary_types = [
        {'code': 'hourly', 'name': 'Hourly', 'order': 1},
        {'code': 'daily', 'name': 'Daily', 'order': 2},
        {'code': 'weekly', 'name': 'Weekly', 'order': 3},
        {'code': 'monthly', 'name': 'Monthly', 'order': 4},
        {'code': 'annually', 'name': 'Annually', 'order': 5},
        {'code': 'fixed_fee', 'name': 'Fixed Fee (Project)', 'order': 6},
    ]
    SalaryType.objects.bulk_create([SalaryType(**sal_type) for sal_type in salary_types])


def reverse_populate(apps, schema_editor):
    """Remove all lookup table data if migration is reversed."""
    JobCategory = apps.get_model('jobs', 'JobCategory')
    EmploymentType = apps.get_model('jobs', 'EmploymentType')
    EducationLevel = apps.get_model('jobs', 'EducationLevel')
    ExperienceLevel = apps.get_model('jobs', 'ExperienceLevel')
    JobLevel = apps.get_model('jobs', 'JobLevel')
    SalaryType = apps.get_model('jobs', 'SalaryType')
    
    JobCategory.objects.all().delete()
    EmploymentType.objects.all().delete()
    EducationLevel.objects.all().delete()
    ExperienceLevel.objects.all().delete()
    JobLevel.objects.all().delete()
    SalaryType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_educationlevel_employmenttype_experiencelevel_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_lookup_tables, reverse_populate),
    ]
