# Generated by Django 4.2.25 on 2025-11-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_populate_lookup_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_jobs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Favorite Job',
                'verbose_name_plural': 'Favorite Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant', '-created_at'], name='jobs_favori_applica_facaa0_idx'), models.Index(fields=['job'], name='jobs_favori_job_id_485154_idx')],
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
