# Generated by Django 4.2.25 on 2025-11-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_favoritejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Stage name (e.g., 'Shortlisted', 'Phone Interview', 'Hired')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the stage (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='The job this stage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='application_stages', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Application Stage',
                'verbose_name_plural': 'Application Stages',
                'ordering': ['job', 'order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Current stage in the hiring pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.applicationstage'),
        ),
        migrations.AddIndex(
            model_name='applicationstage',
            index=models.Index(fields=['job', 'order'], name='jobs_applic_job_id_979012_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationstage',
            unique_together={('job', 'name')},
        ),
    ]
