# Generated by Django 4.2.25 on 2025-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_applicationstage_jobapplication_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstage',
            name='is_system',
            field=models.BooleanField(default=False, help_text="True if this is a system-generated stage (e.g., 'Hired') that cannot be edited/deleted"),
        ),
    ]
