# Generated by Django 4.2.25 on 2025-11-28 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_applicationstage_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(help_text="Name for this alert (e.g., 'Frontend Developer Jobs')", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text='Job title keywords to match', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Preferred job location', max_length=200)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum desired salary', max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum desired salary', max_digits=10, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Additional keywords (comma-separated)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(blank=True, help_text='Preferred job category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alerts', to='jobs.jobcategory')),
                ('job_type', models.ForeignKey(blank=True, help_text='Preferred employment type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_alerts', to='jobs.employmenttype')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='jobs_jobale_user_id_82ec0d_idx'), models.Index(fields=['-created_at'], name='jobs_jobale_created_ca8225_idx')],
            },
        ),
    ]
