# Generated by Django 4.2.25 on 2025-11-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
