# Generated by Django 4.2.25 on 2025-12-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('jobs', '0009_delete_jobtag_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, help_text='Resume submitted with this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume'),
        ),
    ]
