# Generated by Django 4.2.25 on 2025-11-25 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_alter_applicantsociallink_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_profile_rel', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='employer_documents/logos/')),
                ('location', models.JSONField(blank=True, default=dict, help_text='Structured location data, e.g. {"city":"Manila","country":"PH"}', null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='employer_documents/banners/')),
                ('business_permit', models.FileField(blank=True, null=True, upload_to='employer_documents/permits/')),
                ('organization_type', models.CharField(blank=True, choices=[('corp', 'Corporation'), ('llc', 'LLC'), ('solo', 'Sole Proprietorship')], max_length=50, null=True)),
                ('industry_type', models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Healthcare'), ('retail', 'Retail'), ('manu', 'Manufacturing'), ('edu', 'Education'), ('nonprofit', 'Non-Profit'), ('construction', 'Construction'), ('other', 'Other')], max_length=50, null=True)),
                ('team_size', models.CharField(blank=True, choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51+', '51+ Employees')], max_length=20, null=True)),
                ('year_established', models.DateField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_vision', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('setup_step', models.IntegerField(default=1)),
            ],
        ),
    ]
