# Generated by Django 4.2.25 on 2025-11-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Employer Profile', 'verbose_name_plural': 'Employer Profiles'},
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='business_permit',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='setup_step',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_banner_image',
            field=models.ImageField(blank=True, help_text='Large banner image for company profile page', null=True, upload_to='employer_documents/banners/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_business_permit',
            field=models.FileField(blank=True, help_text='Required business registration document for admin verification', null=True, upload_to='employer_documents/permits/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_location_city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_location_country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_location_street',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_profile_image',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='employer_documents/logos/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='contact_phone_number',
            field=models.CharField(blank=True, help_text='Dedicated contact phone number for the company', max_length=20),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically records the last time the profile was modified'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='about_us',
            field=models.TextField(blank=True, help_text="Detailed description of company's mission, culture, etc.", null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, default=' ', help_text='Legal or trade name of the company', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_vision',
            field=models.TextField(blank=True, default=' ', help_text='Long-term vision or statement of the company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(blank=True, default=' ', help_text='Official company website address', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default=' ', help_text='Dedicated contact email for HR/recruitment', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Healthcare'), ('retail', 'Retail'), ('manu', 'Manufacturing'), ('edu', 'Education'), ('nonprofit', 'Non-Profit'), ('construction', 'Construction'), ('other', 'Other')], default=' ', help_text='E.g., Technology, Healthcare, Finance, Manufacturing', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('corp', 'Corporation'), ('llc', 'LLC'), ('solo', 'Sole Proprietorship')], default=' ', help_text='Type of organization', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='team_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51+', '51+ Employees')], default=' ', help_text='Number of employees', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='year_established',
            field=models.DateField(blank=True, help_text='Year the company was founded', null=True),
        ),
    ]
