# Generated by Django 4.2.25 on 2025-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0002_alter_employerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has completed the initial profile setup wizard'),
        ),
    ]
