# Generated by Django 4.2.25 on 2025-11-25 12:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_alter_applicantsociallink_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant_profile_rel', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, default='defaults/default-avatar.png', null=True, upload_to='profile_images/applicant/')),
                ('location', models.JSONField(blank=True, default=dict, help_text='Structured location data, e.g. {"city":"Manila","country":"PH"}', null=True)),
                ('setup_step_progress', models.IntegerField(default=1)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(blank=True, help_text="Professional title or headline (e.g., 'Software Developer' or 'Marketing Specialist')", max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='Contact number must be at least 10 digits.')])),
                ('website', models.URLField(blank=True, help_text='Your personal website, portfolio, or blog URL', max_length=500)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, help_text='e.g., BS in Information Technology', max_length=255)),
                ('year_level', models.CharField(blank=True, help_text='e.g., 3rd Year, Graduate', max_length=50)),
                ('education', models.CharField(blank=True, help_text="Highest education level (e.g., Bachelor's Degree, Master's, PhD)", max_length=255)),
                ('experience', models.CharField(blank=True, help_text="Years of experience (e.g., '0-1 years', '2-5 years', '5+ years')", max_length=100)),
                ('nationality', models.CharField(blank=True, help_text='Your nationality', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Your date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Your gender', max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Your marital status', max_length=20)),
                ('biography', models.TextField(blank=True, help_text='Tell employers about yourself, your experience, and career goals.')),
                ('resume', models.FileField(blank=True, help_text='PDF, DOC, or DOCX only. Max 5MB.', null=True, upload_to='applicant_documents/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('profile_completeness', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True, help_text='Allow employers to view your profile.')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('portfolio', 'Portfolio')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='applicant_profile.applicantprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
