# Generated by Django 4.2.25 on 2025-11-25 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Applicant Profile', 'verbose_name_plural': 'Applicant Profiles'},
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='profile_completeness',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='setup_step_progress',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='year_level',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate/PhD'), ('vocational', 'Vocational/Technical')], help_text='Highest education level attained', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='location_city',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='location_country',
            field=models.CharField(blank=True, help_text='Country of residence', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='location_street',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Applicant's profile picture", null=True, upload_to='applicant_documents/profile_images/'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically records the last time the profile was modified'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='biography',
            field=models.TextField(blank=True, help_text="Brief 'About Me' or summary section"),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='contact_number',
            field=models.CharField(blank=True, help_text="Applicant's contact phone number", max_length=20, validators=[django.core.validators.MinLengthValidator(10, message='Contact number must be at least 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='For age verification or demographic data', null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], help_text="Years of experience (e.g., '0-1 years', '2-5 years', '5+ years')", max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer Not to Say')], help_text='Gender identification', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether the applicant profile is visible to employers/public'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('prefer_not_to_say', 'Prefer Not to Say')], help_text='Marital status information', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='nationality',
            field=models.CharField(blank=True, help_text="Applicant's nationality", max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume/CV document (PDF, DOC, or DOCX)', null=True, upload_to='applicant_documents/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='title',
            field=models.CharField(blank=True, help_text="Professional title (e.g., 'Senior Frontend Developer')", max_length=200),
        ),
        migrations.DeleteModel(
            name='ApplicantSocialLink',
        ),
    ]
