# Generated by Django 4.2.25 on 2025-11-28 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_user_is_verified_remove_user_middle_name'),
        ('applicant_profile', '0002_alter_applicantprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notify_shortlisted', models.BooleanField(default=True, help_text='Notify when shortlisted by employers')),
                ('notify_applications', models.BooleanField(default=True, help_text='Notify when application status changes')),
                ('notify_job_alerts', models.BooleanField(default=True, help_text='Notify about new jobs matching job alert preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
