# Generated by Django 4.2.25 on 2025-12-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profile', '0003_notificationpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='resume',
        ),
    ]
