# Generated by Django 4.2.25 on 2025-12-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profile', '0004_remove_resume_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has completed the initial profile setup wizard'),
        ),
    ]
