# Generated by Django 4.2.25 on 2025-11-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('portfolio', 'Portfolio')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.applicantprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
