# Generated by Django 4.2.25 on 2025-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_applicantsociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='biography',
            field=models.TextField(blank=True, help_text='Tell employers about yourself, your experience, and career goals.'),
        ),
    ]
