# Generated by Django 4.2.25 on 2025-11-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_applicantprofile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='employer_documents/banners/'),
        ),
    ]
