# Generated by Django 4.2.25 on 2025-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Your date of birth', null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='education',
            field=models.CharField(blank=True, help_text="Highest education level (e.g., Bachelor's Degree, Master's, PhD)", max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='experience',
            field=models.CharField(blank=True, help_text="Years of experience (e.g., '0-1 years', '2-5 years', '5+ years')", max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Your gender', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Your marital status', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='nationality',
            field=models.CharField(blank=True, help_text='Your nationality', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='title',
            field=models.CharField(blank=True, help_text="Professional title or headline (e.g., 'Software Developer' or 'Marketing Specialist')", max_length=200),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal website, portfolio, or blog URL', max_length=500),
        ),
    ]
