# Generated by Django 4.2.25 on 2025-11-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_applicantprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='skills_summary',
        ),
    ]
