# Generated by Django 4.2.25 on 2025-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_applicantprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='location',
            field=models.JSONField(blank=True, default=dict, help_text='Structured location data, e.g. {"city":"Manila","country":"PH"}', null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.JSONField(blank=True, default=dict, help_text='Structured location data, e.g. {"city":"Manila","country":"PH"}', null=True),
        ),
    ]
