# Generated by Django 4.2.25 on 2025-11-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_applicantprofile_location_employerprofile_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantsociallink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='applicantsociallink',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApplicantProfile',
        ),
        migrations.DeleteModel(
            name='ApplicantSocialLink',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
