# Generated by Django 4.2.25 on 2025-11-25 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_applicantsociallink_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, help_text='Timestamp of the last status update', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin comments on the verification decision')),
                ('admin_verifier', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Verification',
                'verbose_name_plural': 'User Verifications',
            },
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('website', 'Website'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Social Link',
                'verbose_name_plural': 'User Social Links',
                'ordering': ['created_at'],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
