from jobs.models import Job

def load_sample_jobs():
    sample_jobs = [
        {
            "title": "Software Engineer",
            "description": "Develop and maintain software applications.",
            "job_type": "FT",
            "industry": "Information Technology",
            "salary_min": 35000,
            "salary_max": 60000,
            "location": "Cebu City",
            "is_remote": False,
        },
        {
            "title": "Frontend Developer",
            "description": "Develop modern UI for web applications.",
            "job_type": "FT",
            "industry": "Information Technology",
            "salary_min": 30000,
            "salary_max": 50000,
            "location": "Remote",
            "is_remote": True,
        },
        {
            "title": "Marketing Specialist",
            "description": "Plan and execute marketing campaigns.",
            "job_type": "FT",
            "industry": "Marketing",
            "salary_min": 25000,
            "salary_max": 40000,
            "location": "Manila",
            "is_remote": False,
        },
        {
            "title": "Graphic Designer",
            "description": "Create visual assets for branding and marketing.",
            "job_type": "PT",
            "industry": "Design",
            "salary_min": 15000,
            "salary_max": 25000,
            "location": "Cebu City",
            "is_remote": False,
        },
        {
            "title": "Data Analyst",
            "description": "Analyze data to generate insightful reports.",
            "job_type": "FT",
            "industry": "Data Science",
            "salary_min": 40000,
            "salary_max": 70000,
            "location": "Makati",
            "is_remote": False,
        },
        {
            "title": "UI/UX Designer",
            "description": "Design intuitive user interfaces.",
            "job_type": "CT",
            "industry": "Design",
            "salary_min": 20000,
            "salary_max": 35000,
            "location": "Remote",
            "is_remote": True,
        },
        {
            "title": "Accountant",
            "description": "Handle business financial documents.",
            "job_type": "FT",
            "industry": "Finance",
            "salary_min": 25000,
            "salary_max": 45000,
            "location": "Davao City",
            "is_remote": False,
        },
        {
            "title": "HR Assistant",
            "description": "Assist with HR documentation and screening.",
            "job_type": "IN",
            "industry": "Human Resources",
            "salary_min": 8000,
            "salary_max": 12000,
            "location": "Cebu City",
            "is_remote": False,
        },
        {
            "title": "Nurse",
            "description": "Provide healthcare support to patients.",
            "job_type": "FT",
            "industry": "Healthcare",
            "salary_min": 20000,
            "salary_max": 30000,
            "location": "Manila",
            "is_remote": False,
        },
        {
            "title": "Customer Support",
            "description": "Assist customers with inquiries.",
            "job_type": "FT",
            "industry": "Customer Service",
            "salary_min": 15000,
            "salary_max": 20000,
            "location": "Remote",
            "is_remote": True,
        },
    ]

    for job_data in sample_jobs:
        Job.objects.create(**job_data)

    print("Sample jobs inserted successfully!")
