# Generated by Django 4.2.25 on 2025-11-29 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_received', 'Application Received'), ('application_status', 'Application Status Update'), ('application_shortlist', 'Application Shortlisted'), ('application_rejected', 'Application Rejected'), ('application_hired', 'Application Hired'), ('job_posted', 'Job Posted'), ('job_alert', 'Job Alert Match'), ('system', 'System Notification')], default='system', help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('link', models.CharField(blank=True, help_text='Optional link for this notification', max_length=500)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When this notification was read', null=True)),
                ('related_job_id', models.IntegerField(blank=True, help_text='ID of related job (if applicable)', null=True)),
                ('related_application_id', models.IntegerField(blank=True, help_text='ID of related application (if applicable)', null=True)),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
